export type GitHubCopilotPlan = {
  id: string;
  label: string;
  monthlyCredits: number | null;
  sharedPool?: boolean;
};

export const GITHUB_COPILOT_PLANS: GitHubCopilotPlan[] = [
  { id: "free", label: "Copilot Free", monthlyCredits: null },
  { id: "student", label: "Copilot Student", monthlyCredits: null },
  { id: "pro", label: "Copilot Pro", monthlyCredits: 1500 },
  { id: "pro-plus", label: "Copilot Pro+", monthlyCredits: 7000 },
  { id: "max", label: "Copilot Max", monthlyCredits: 20000 },
  {
    id: "business",
    label: "Copilot Business",
    monthlyCredits: 1900,
    sharedPool: true,
  },
  {
    id: "enterprise",
    label: "Copilot Enterprise",
    monthlyCredits: 3900,
    sharedPool: true,
  },
];

export type GitHubCopilotModelRate = {
  id: string;
  label: string;
  provider: string;
  inputUsdPerMillion: number;
  cachedInputUsdPerMillion: number;
  cacheWriteUsdPerMillion?: number;
  outputUsdPerMillion: number;
};

// Rate snapshot from GitHub's public models-and-pricing page, checked 2026-09-23.
export const GITHUB_COPILOT_MODEL_RATES: GitHubCopilotModelRate[] = [
  {
    id: "gpt-5-mini",
    label: "GPT-5 mini",
    provider: "OpenAI",
    inputUsdPerMillion: 0.25,
    cachedInputUsdPerMillion: 0.025,
    outputUsdPerMillion: 2,
  },
  {
    id: "gpt-5-3-codex",
    label: "GPT-5.3-Codex",
    provider: "OpenAI",
    inputUsdPerMillion: 1.75,
    cachedInputUsdPerMillion: 0.175,
    outputUsdPerMillion: 14,
  },
  {
    id: "gpt-5-4",
    label: "GPT-5.4 (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 2.5,
    cachedInputUsdPerMillion: 0.25,
    outputUsdPerMillion: 15,
  },
  {
    id: "gpt-5-4-long",
    label: "GPT-5.4 (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 22.5,
  },
  {
    id: "gpt-5-4-mini",
    label: "GPT-5.4 mini",
    provider: "OpenAI",
    inputUsdPerMillion: 0.75,
    cachedInputUsdPerMillion: 0.075,
    outputUsdPerMillion: 4.5,
  },
  {
    id: "gpt-5-4-nano",
    label: "GPT-5.4 nano",
    provider: "OpenAI",
    inputUsdPerMillion: 0.2,
    cachedInputUsdPerMillion: 0.02,
    outputUsdPerMillion: 1.25,
  },
  {
    id: "gpt-5-5",
    label: "GPT-5.5 (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 30,
  },
  {
    id: "gpt-5-5-long",
    label: "GPT-5.5 (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 10,
    cachedInputUsdPerMillion: 1,
    outputUsdPerMillion: 45,
  },
  {
    id: "gpt-5-6-luna",
    label: "GPT-5.6 Luna (default context, up to 200K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 0.2,
    cachedInputUsdPerMillion: 0.02,
    cacheWriteUsdPerMillion: 0.25,
    outputUsdPerMillion: 1.2,
  },
  {
    id: "gpt-5-6-luna-long",
    label: "GPT-5.6 Luna (long context, over 200K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 0.4,
    cachedInputUsdPerMillion: 0.04,
    cacheWriteUsdPerMillion: 0.5,
    outputUsdPerMillion: 1.8,
  },
  {
    id: "gpt-5-6-sol",
    label: "GPT-5.6 Sol (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 0.4,
    cacheWriteUsdPerMillion: 5,
    outputUsdPerMillion: 20,
  },
  {
    id: "gpt-5-6-sol-long",
    label: "GPT-5.6 Sol (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 8,
    cachedInputUsdPerMillion: 0.8,
    cacheWriteUsdPerMillion: 10,
    outputUsdPerMillion: 30,
  },
  {
    id: "gpt-5-6-terra",
    label: "GPT-5.6 Terra (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.2,
    cacheWriteUsdPerMillion: 2.5,
    outputUsdPerMillion: 12,
  },
  {
    id: "gpt-5-6-terra-long",
    label: "GPT-5.6 Terra (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 0.4,
    cacheWriteUsdPerMillion: 5,
    outputUsdPerMillion: 18,
  },
  {
    id: "gpt-6-astra",
    label: "GPT-6 Astra (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 10,
    cachedInputUsdPerMillion: 1,
    cacheWriteUsdPerMillion: 12.5,
    outputUsdPerMillion: 50,
  },
  {
    id: "gpt-6-astra-long",
    label: "GPT-6 Astra (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 20,
    cachedInputUsdPerMillion: 2,
    cacheWriteUsdPerMillion: 25,
    outputUsdPerMillion: 75,
  },
  {
    id: "gpt-6-luna",
    label: "GPT-6 Luna (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 0.1,
    cachedInputUsdPerMillion: 0.01,
    cacheWriteUsdPerMillion: 0.125,
    outputUsdPerMillion: 0.5,
  },
  {
    id: "gpt-6-luna-long",
    label: "GPT-6 Luna (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 0.2,
    cachedInputUsdPerMillion: 0.02,
    cacheWriteUsdPerMillion: 0.25,
    outputUsdPerMillion: 0.75,
  },
  {
    id: "gpt-6-sol",
    label: "GPT-6 Sol (default context, up to 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.2,
    cacheWriteUsdPerMillion: 2.5,
    outputUsdPerMillion: 10,
  },
  {
    id: "gpt-6-sol-long",
    label: "GPT-6 Sol (long context, over 272K input tokens)",
    provider: "OpenAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 0.4,
    cacheWriteUsdPerMillion: 5,
    outputUsdPerMillion: 15,
  },
  {
    id: "claude-haiku-4-5",
    label: "Claude Haiku 4.5",
    provider: "Anthropic",
    inputUsdPerMillion: 1,
    cachedInputUsdPerMillion: 0.1,
    cacheWriteUsdPerMillion: 1.25,
    outputUsdPerMillion: 5,
  },
  {
    id: "claude-sonnet-4",
    label: "Claude Sonnet 4",
    provider: "Anthropic",
    inputUsdPerMillion: 3,
    cachedInputUsdPerMillion: 0.3,
    cacheWriteUsdPerMillion: 3.75,
    outputUsdPerMillion: 15,
  },
  {
    id: "claude-sonnet-4-6",
    label: "Claude Sonnet 4.6",
    provider: "Anthropic",
    inputUsdPerMillion: 3,
    cachedInputUsdPerMillion: 0.3,
    cacheWriteUsdPerMillion: 3.75,
    outputUsdPerMillion: 15,
  },
  {
    id: "claude-opus-4-7",
    label: "Claude Opus 4.7",
    provider: "Anthropic",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    cacheWriteUsdPerMillion: 6.25,
    outputUsdPerMillion: 25,
  },
  {
    id: "claude-opus-4-8",
    label: "Claude Opus 4.8",
    provider: "Anthropic",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    cacheWriteUsdPerMillion: 6.25,
    outputUsdPerMillion: 25,
  },
  {
    id: "claude-opus-5",
    label: "Claude Opus 5",
    provider: "Anthropic",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    cacheWriteUsdPerMillion: 6.25,
    outputUsdPerMillion: 25,
  },
  {
    id: "claude-opus-5-5",
    label: "Claude Opus 5.5",
    provider: "Anthropic",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 0.2,
    cacheWriteUsdPerMillion: 5,
    outputUsdPerMillion: 20,
  },
  {
    id: "claude-sonnet-5",
    label: "Claude Sonnet 5",
    provider: "Anthropic",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.2,
    cacheWriteUsdPerMillion: 2.5,
    outputUsdPerMillion: 10,
  },
  {
    id: "claude-opus-4-8-fast",
    label: "Claude Opus 4.8 (fast mode)",
    provider: "Anthropic",
    inputUsdPerMillion: 10,
    cachedInputUsdPerMillion: 1,
    cacheWriteUsdPerMillion: 12.5,
    outputUsdPerMillion: 50,
  },
  {
    id: "claude-fable-5",
    label: "Claude Fable 5",
    provider: "Anthropic",
    inputUsdPerMillion: 10,
    cachedInputUsdPerMillion: 1,
    cacheWriteUsdPerMillion: 12.5,
    outputUsdPerMillion: 50,
  },
  {
    id: "claude-fable-5-1",
    label: "Claude Fable 5.1",
    provider: "Anthropic",
    inputUsdPerMillion: 10,
    cachedInputUsdPerMillion: 0.25,
    cacheWriteUsdPerMillion: 12.5,
    outputUsdPerMillion: 50,
  },
  {
    id: "gemini-3-5-flash",
    label: "Gemini 3.5 Flash",
    provider: "Google",
    inputUsdPerMillion: 1.5,
    cachedInputUsdPerMillion: 0.15,
    outputUsdPerMillion: 9,
  },
  {
    id: "gemini-3-6-flash",
    label: "Gemini 3.6 Flash (promotional rate through 2026-12-31)",
    provider: "Google",
    inputUsdPerMillion: 0.75,
    cachedInputUsdPerMillion: 0.075,
    outputUsdPerMillion: 3.75,
  },
  {
    id: "gemini-3-7-flash",
    label: "Gemini 3.7 Flash (promotional rate through 2026-12-31)",
    provider: "Google",
    inputUsdPerMillion: 0.75,
    cachedInputUsdPerMillion: 0.075,
    outputUsdPerMillion: 3.75,
  },
  {
    id: "gemini-3-8-flash",
    label: "Gemini 3.8 Flash (promotional rate through 2026-12-31)",
    provider: "Google",
    inputUsdPerMillion: 0.75,
    cachedInputUsdPerMillion: 0.075,
    outputUsdPerMillion: 3.75,
  },
  {
    id: "mai-code-1-1-flash",
    label: "MAI-Code-1.1-Flash",
    provider: "Microsoft",
    inputUsdPerMillion: 0.2,
    cachedInputUsdPerMillion: 0.02,
    outputUsdPerMillion: 1.2,
  },
  {
    id: "grok-4-5",
    label: "Grok 4.5 (default context, up to 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 6,
  },
  {
    id: "grok-4-5-long",
    label: "Grok 4.5 (long context, over 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 1,
    outputUsdPerMillion: 12,
  },
  {
    id: "grok-4-6",
    label: "Grok 4.6 (default context, up to 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 6,
  },
  {
    id: "grok-4-6-long",
    label: "Grok 4.6 (long context, over 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 1,
    outputUsdPerMillion: 12,
  },
  {
    id: "grok-4-7",
    label: "Grok 4.7 (default context, up to 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 2,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 6,
  },
  {
    id: "grok-4-7-long",
    label: "Grok 4.7 (long context, over 200K input tokens)",
    provider: "xAI",
    inputUsdPerMillion: 4,
    cachedInputUsdPerMillion: 1,
    outputUsdPerMillion: 12,
  },
  {
    id: "kimi-k2-7-code",
    label: "Kimi K2.7 Code",
    provider: "Moonshot AI",
    inputUsdPerMillion: 0.95,
    cachedInputUsdPerMillion: 0.19,
    outputUsdPerMillion: 4,
  },
  {
    id: "kimi-k3",
    label: "Kimi K3",
    provider: "Moonshot AI",
    inputUsdPerMillion: 3,
    cachedInputUsdPerMillion: 0.3,
    outputUsdPerMillion: 15,
  },
];
